"use strict";
const $=id=>document.getElementById(id), clean=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim(), fmt=n=>Number(n||0).toLocaleString('es-MX'), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let meta,schools=[],visible=[],programMap=new Map(),schoolLayer=L.layerGroup(),cpLayer,colLayer,alcaldiasLayer,selectedMarker=null;
const map=L.map('map',{zoomControl:false,preferCanvas:true,minZoom:9}).setView([19.35,-99.13],10); L.control.zoom({position:'topright'}).addTo(map);
const baseLayers={'OpenStreetMap':L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap'}),'Claro':L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:20,attribution:'© OpenStreetMap © CARTO'}),'Oscuro':L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:20,attribution:'© OpenStreetMap © CARTO'})};baseLayers.Claro.addTo(map);L.control.layers(baseLayers,{}, {collapsed:true,position:'bottomright'}).addTo(map);schoolLayer.addTo(map);
Promise.all([fetch('data/manifest.json').then(r=>r.json()),fetch('data/codigos_postales.geojson').then(r=>r.json()),fetch('data/colonias_asentamientos.geojson').then(r=>r.json()),fetch('data/alcaldias.json').then(r=>r.json())]).then(async([m,cps,cols,alcs])=>{meta=m;programMap=new Map(m.programas.map(p=>[p.id,p]));schools=(await Promise.all(m.partes.map(f=>fetch('data/'+f).then(r=>r.json())))).flat(); setupBoundaries(cps,cols,alcs); buildControls(); bind(); render(); $('loading').style.display='none';}).catch(e=>{$('loading').textContent='Error al cargar los datos';console.error(e)});
function setupBoundaries(cps,cols,alcs){alcaldiasLayer=L.geoJSON(alcs,{style:{color:'#45677e',weight:1,fillOpacity:.015,dashArray:'4 3'},interactive:false}).addTo(map);cpLayer=L.geoJSON(cps,{style:f=>polyStyle(f.properties.escuelas,'cp'),onEachFeature:(f,l)=>{l.bindTooltip(`<b>CP ${esc(f.properties.cp)}</b><br>${fmt(f.properties.escuelas)} CCT`);l.on('click',()=>{$('fCP').value=f.properties.cp;render();});}});colLayer=L.geoJSON(cols,{style:f=>polyStyle(f.properties.escuelas,'col'),onEachFeature:(f,l)=>{l.bindTooltip(`<b>${esc(f.properties.nom_asen)}</b><br>${esc(f.properties.tipo)} · CP ${esc(f.properties.cp)}<br>${fmt(f.properties.escuelas)} CCT`);l.on('click',()=>{$('fColonia').value=f.properties.cvegeo;render();});}})}
function polyStyle(n,type){let x=Number(n||0),op=x?Math.min(.55,.12+Math.log10(x+1)*.18):.035;return {color:type==='cp'?'#315f85':'#7b4b8f',weight:.8,fillColor:type==='cp'?'#3979a8':'#9b6aae',fillOpacity:op}}
function buildControls(){fill($('fAlcaldia'),[...new Set(schools.map(x=>x.alcaldia).filter(Boolean))].sort());fill($('fNivel'),[...new Set(schools.map(x=>x.nivel).filter(Boolean))].sort());fill($('fCP'),[...new Set(schools.map(x=>x.cp).filter(Boolean))].sort());let cols=[...new Map(schools.filter(x=>x.cvegeo_asentamiento).map(x=>[x.cvegeo_asentamiento,{id:x.cvegeo_asentamiento,label:`${x.asentamiento} · ${x.tipo_asentamiento||'Asentamiento'} · CP ${x.cp||'—'}`}])).values()].sort((a,b)=>a.label.localeCompare(b.label,'es'));cols.forEach(o=>$('fColonia').add(new Option(o.label,o.id)));$('programFilters').innerHTML=meta.programas.map(p=>`<label><input type="checkbox" value="${esc(p.id)}"><span class="program-dot" style="background:${esc(p.color)}"></span>${esc(p.label)}</label>`).join(''); $('cctList').innerHTML=schools.map(x=>`<option value="${esc(x.cct)}">`).join(''); $('nameList').innerHTML=[...new Set(schools.map(x=>x.nombre).filter(Boolean))].sort().map(x=>`<option value="${esc(x)}">`).join('');}
function fill(sel,arr){arr.forEach(v=>sel.add(new Option(v,v)))}
function bind(){['fAlcaldia','fNivel','fCP','fColonia','colorMode'].forEach(id=>$(id).addEventListener('change',render));document.querySelectorAll('input[name=soste]').forEach(x=>x.addEventListener('change',render));$('programFilters').addEventListener('change',render);$('showCP').onchange=()=>toggleLayer(cpLayer,$('showCP').checked);$('showColonias').onchange=()=>toggleLayer(colLayer,$('showColonias').checked);$('showSchools').onchange=render;$('allProg').onclick=()=>{document.querySelectorAll('#programFilters input').forEach(x=>x.checked=true);render()};$('noneProg').onclick=()=>{document.querySelectorAll('#programFilters input').forEach(x=>x.checked=false);render()};$('clearFilters').onclick=()=>{['fAlcaldia','fNivel','fCP','fColonia','searchCCT','searchName'].forEach(id=>$(id).value='');document.querySelectorAll('input[name=soste]').forEach(x=>x.checked=true);document.querySelectorAll('#programFilters input').forEach(x=>x.checked=false);render()};$('searchCCT').addEventListener('change',searchZoom);$('searchCCT').addEventListener('keydown',e=>{if(e.key==='Enter')searchZoom()});$('searchName').addEventListener('change',searchZoom);$('searchName').addEventListener('keydown',e=>{if(e.key==='Enter')searchZoom()});$('closeDetail').onclick=()=> $('detail').classList.remove('open');$('fitAll').onclick=()=>alcaldiasLayer&&map.fitBounds(alcaldiasLayer.getBounds(),{padding:[10,10]});$('fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');}
function toggleLayer(layer,on){if(on){if(!map.hasLayer(layer))layer.addTo(map);layer.bringToBack();alcaldiasLayer?.bringToBack()}else if(map.hasLayer(layer))map.removeLayer(layer)}
function state(){return {alcaldia:$('fAlcaldia').value,nivel:$('fNivel').value,cp:$('fCP').value,col:$('fColonia').value,soste:new Set([...document.querySelectorAll('input[name=soste]:checked')].map(x=>x.value)),progs:new Set([...document.querySelectorAll('#programFilters input:checked')].map(x=>x.value))}}
function filtered(){let s=state();return schools.filter(x=>{if(s.alcaldia&&x.alcaldia!==s.alcaldia)return false;if(s.nivel&&x.nivel!==s.nivel)return false;if(s.cp&&x.cp!==s.cp)return false;if(s.col&&x.cvegeo_asentamiento!==s.col)return false;if(!s.soste.has(x.sostenimiento))return false;if(s.progs.size&&!x.programas.some(p=>s.progs.has(p)))return false;return true})}
function render(){visible=filtered();updateKPIs();renderSchools();renderLegend();highlightPolygons();}
function updateKPIs(){$('kTotal').textContent=fmt(visible.length);$('kPub').textContent=fmt(visible.filter(x=>x.sostenimiento==='Público').length);$('kPri').textContent=fmt(visible.filter(x=>x.sostenimiento==='Privada').length);$('kProg').textContent=fmt(visible.filter(x=>x.programas.length).length);let s=state(),parts=[];if(s.cp)parts.push('CP '+s.cp);if(s.col){let x=visible[0]||schools.find(y=>y.cvegeo_asentamiento===s.col);if(x)parts.push(x.asentamiento)};if(s.alcaldia)parts.push(s.alcaldia);if(s.nivel)parts.push(s.nivel);$('scopeNote').textContent=parts.length?'Conteo actual: '+parts.join(' · '):`Base completa: ${fmt(meta.total_cct_unicos)} CCT únicos de ${fmt(meta.total_filas_fuente)} filas fuente.`}
function renderSchools(){schoolLayer.clearLayers();if(!$('showSchools').checked)return;let mode=$('colorMode').value;for(const x of visible){if(!Number.isFinite(x.lat)||!Number.isFinite(x.lon))continue;let c=colorFor(x,mode);let m=L.circleMarker([x.lat,x.lon],{radius:5,color:'#fff',weight:1,fillColor:c,fillOpacity:.86});m.bindTooltip(`<b>${esc(x.nombre)}</b><br>${esc(x.cct)} · ${esc(x.nivel)}`);m.on('click',()=>showDetail(x));m.addTo(schoolLayer)}}
const levelColors=['#2f6da5','#b05b6f','#638b48','#a06d2c','#7257a3','#2e8a89','#a45030','#55707f','#91648a','#5a7b57'];function colorFor(x,mode){if(mode==='sostenimiento')return x.sostenimiento==='Privada'?'#8b5fa5':'#1f78a8';if(mode==='programa')return x.programas.length?'#c65e2e':'#748594';let levels=meta.niveles||[];return levelColors[Math.max(0,levels.indexOf(x.nivel))%levelColors.length]}
function renderLegend(){let mode=$('colorMode').value,h='<b>Leyenda</b>';if(mode==='sostenimiento')h+='<div><i class="swatch" style="background:#1f78a8"></i>Pública</div><div><i class="swatch" style="background:#8b5fa5"></i>Privada</div>';else if(mode==='programa')h+='<div><i class="swatch" style="background:#c65e2e"></i>Con programa</div><div><i class="swatch" style="background:#748594"></i>Sin programa</div>';else h+=(meta.niveles||[]).map((n,i)=>`<div><i class="swatch" style="background:${levelColors[i%levelColors.length]}"></i>${esc(n)}</div>`).join('');$('legend').innerHTML=h}
function highlightPolygons(){let s=state();if(cpLayer)cpLayer.eachLayer(l=>{let hit=s.cp&&l.feature.properties.cp===s.cp;l.setStyle({...polyStyle(l.feature.properties.escuelas,'cp'),weight:hit?3:.8,fillOpacity:hit?.55:polyStyle(l.feature.properties.escuelas,'cp').fillOpacity})});if(colLayer)colLayer.eachLayer(l=>{let hit=s.col&&l.feature.properties.cvegeo===s.col;l.setStyle({...polyStyle(l.feature.properties.escuelas,'col'),weight:hit?3:.8,fillOpacity:hit?.55:polyStyle(l.feature.properties.escuelas,'col').fillOpacity})})}
function showDetail(x){$('detailTitle').textContent=x.nombre||x.cct;let prog=x.programas.length?`<div class="pills">${x.programas.map(id=>{let p=programMap.get(id);return `<span class="pill" style="border-left:3px solid ${esc(p?.color||'#789')}">${esc(p?.label||id)}</span>`}).join('')}</div>`:'Sin programa vinculado en el ZIP base';$('detailBody').innerHTML=`<dl><dt>CCT</dt><dd>${esc(x.cct)}</dd><dt>Sostenimiento</dt><dd>${esc(x.sostenimiento)}</dd><dt>Nivel</dt><dd>${esc(x.nivel)}</dd><dt>Alcaldía</dt><dd>${esc(x.alcaldia)}</dd><dt>CP</dt><dd>${esc(x.cp||'Sin coincidencia espacial')}</dd><dt>Asentamiento</dt><dd>${esc(x.asentamiento||'Sin coincidencia espacial')} ${x.tipo_asentamiento?`(${esc(x.tipo_asentamiento)})`:''}</dd><dt>Colonia base</dt><dd>${esc(x.colonia_base||'Sin dato')}</dd><dt>Domicilio</dt><dd>${esc(x.domicilio||'Sin dato')}</dd><dt>Programas</dt><dd>${prog}</dd><dt>Coordenadas</dt><dd>${x.lat?.toFixed(6)}, ${x.lon?.toFixed(6)}</dd></dl>`;$('detail').classList.add('open')}
function searchZoom(){let c=clean($('searchCCT').value),n=clean($('searchName').value);let x=schools.find(s=>(c&&clean(s.cct)===c)||(n&&clean(s.nombre)===n));if(!x)return;if(Number.isFinite(x.lat)&&Number.isFinite(x.lon)){map.setView([x.lat,x.lon],17);showDetail(x)}if(innerWidth<800)$('sidebar').classList.remove('open')}
