"use strict";
const $=id=>document.getElementById(id),clean=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim(),fmt=n=>Number(n||0).toLocaleString('es-MX'),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let meta,schools=[],visible=[],inmuebles=[],visibleInm=[],programMap=new Map(),currentInm=null,alcGeo,cpGeo,colGeo,alcLabels=[];
const lightStyle={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'bg',type:'background',paint:{'background-color':'#eef3f6'}},{id:'osm',type:'raster',source:'osm',paint:{'raster-opacity':.95}}]};
const darkStyle={version:8,sources:{},layers:[{id:'bg',type:'background',paint:{'background-color':'#17222b'}}]};
const map=new maplibregl.Map({container:'map',style:lightStyle,center:[-99.13,19.35],zoom:9.65,pitch:0,bearing:0,antialias:true,maxZoom:19});
map.addControl(new maplibregl.NavigationControl({showCompass:true}),'top-right');
Promise.all([fetch('data/manifest.json').then(r=>r.json()),fetch('data/codigos_postales.geojson').then(r=>r.json()),fetch('data/colonias_asentamientos.geojson').then(r=>r.json()),fetch('data/alcaldias.json').then(r=>r.json())]).then(async([m,cps,cols,alcs])=>{meta=m;programMap=new Map(m.programas.map(p=>[p.id,p]));schools=(await Promise.all(m.partes.map(f=>fetch('data/'+f).then(r=>r.json())))).flat();inmuebles=buildInmuebles(schools);alcGeo=decorateAlcaldias(alcs);cpGeo=decorateCP(cps);colGeo=decorateCols(cols);buildControls();bind();map.on('load',()=>{installMapLayers();render();fitGeo(alcGeo,{pitch:0});$('loading').style.display='none'});}).catch(e=>{$('loading').textContent='Error al cargar los datos';console.error(e)});
function buildInmuebles(arr){const groups=new Map();for(const s of arr){if(!Number.isFinite(s.lat)||!Number.isFinite(s.lon))continue;const key=`${s.lat.toFixed(6)},${s.lon.toFixed(6)}`;if(!groups.has(key))groups.set(key,{id:'INM-'+String(groups.size+1).padStart(5,'0'),key,lat:s.lat,lon:s.lon,ccts:new Map(),alcaldia:s.alcaldia||'',cp:s.cp||'',col:s.cvegeo_asentamiento||'',asentamiento:s.asentamiento||'',tipo:s.tipo_asentamiento||'',domicilio:s.domicilio||''});const g=groups.get(key);if(!g.ccts.has(s.cct))g.ccts.set(s.cct,s)}return [...groups.values()].map(g=>({...g,ccts:[...g.ccts.values()]}))}
function decorateAlcaldias(g){const by=new Map();for(const i of inmuebles){const k=clean(i.alcaldia);if(!by.has(k))by.set(k,{inm:0,cct:new Set(),pub:0,pri:0,niv:new Map()});const o=by.get(k);o.inm++;for(const c of i.ccts){o.cct.add(c.cct);if(c.sostenimiento==='Público')o.pub++;else if(c.sostenimiento==='Privada')o.pri++;o.niv.set(c.nivel,(o.niv.get(c.nivel)||0)+1)}}for(const f of g.features){const o=by.get(clean(f.properties.NOMGEO))||{inm:0,cct:new Set(),pub:0,pri:0,niv:new Map()};f.properties.inmuebles=o.inm;f.properties.cct=o.cct.size;f.properties.publicas=o.pub;f.properties.privadas=o.pri;f.properties.topniv=[...o.niv].sort((a,b)=>b[1]-a[1]).slice(0,2).map(x=>`${x[0]} ${x[1]}`).join(' · ')}return g}
function decorateCP(g){const counts=new Map();for(const i of inmuebles)if(i.cp)counts.set(i.cp,(counts.get(i.cp)||0)+1);for(const f of g.features){f.properties.inmuebles=counts.get(String(f.properties.cp))||0}return g}
function decorateCols(g){const counts=new Map();for(const i of inmuebles)if(i.col)counts.set(i.col,(counts.get(i.col)||0)+1);for(const f of g.features){f.properties.inmuebles=counts.get(String(f.properties.cvegeo))||0}return g}
function installMapLayers(){map.addSource('alcaldias',{type:'geojson',data:alcGeo});map.addSource('cp',{type:'geojson',data:cpGeo});map.addSource('colonias',{type:'geojson',data:colGeo});map.addSource('schools',{type:'geojson',data:{type:'FeatureCollection',features:[]}});
map.addLayer({id:'alc-extrude',type:'fill-extrusion',source:'alcaldias',paint:{'fill-extrusion-color':['case',['==',['get','selected'],1],'#d05d61','#8aa8be'],'fill-extrusion-height':['case',['==',['get','selected'],1],2800,70],'fill-extrusion-base':0,'fill-extrusion-opacity':.72}});
map.addLayer({id:'alc-line',type:'line',source:'alcaldias',paint:{'line-color':'#536c7d','line-width':1.2}});
map.addLayer({id:'cp-extrude',type:'fill-extrusion',source:'cp',layout:{visibility:'none'},paint:{'fill-extrusion-color':['case',['==',['get','selected'],1],'#3979a8',['==',['get','inmuebles'],0],'#d4d9dd','#8eb1c8'],'fill-extrusion-height':['case',['==',['get','selected'],1],1800,35],'fill-extrusion-opacity':.65}});
map.addLayer({id:'col-extrude',type:'fill-extrusion',source:'colonias',layout:{visibility:'none'},paint:{'fill-extrusion-color':['case',['==',['get','selected'],1],'#9b6aae',['==',['get','inmuebles'],0],'#ddd7df','#c2a7cc'],'fill-extrusion-height':['case',['==',['get','selected'],1],1200,25],'fill-extrusion-opacity':.64}});
map.addLayer({id:'schools',type:'circle',source:'schools',paint:{'circle-radius':4.5,'circle-color':['get','color'],'circle-stroke-width':1,'circle-stroke-color':'#fff','circle-opacity':.88}});
map.on('click','schools',e=>{const id=e.features?.[0]?.properties?.idx;const x=schools[Number(id)];if(x)showDetail(x)});map.on('mouseenter','schools',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','schools',()=>map.getCanvas().style.cursor='');
map.on('click','cp-extrude',e=>{const v=e.features?.[0]?.properties?.cp;if(v){$('fCP').value=v;render();activateTerritory3D('cp',v)}});map.on('click','col-extrude',e=>{const v=e.features?.[0]?.properties?.cvegeo;if(v){$('fColonia').value=v;render();activateTerritory3D('colonia',v)}});
}
function buildControls(){fill($('fAlcaldia'),[...new Set(schools.map(x=>x.alcaldia).filter(Boolean))].sort());fill($('fNivel'),[...new Set(schools.map(x=>x.nivel).filter(Boolean))].sort());refreshCPOptions();refreshColOptions();$('programFilters').innerHTML=meta.programas.map(p=>`<label><input type="checkbox" value="${esc(p.id)}"><span class="program-dot" style="background:${esc(p.color)}"></span>${esc(p.label)}</label>`).join('');$('cctList').innerHTML=schools.map(x=>`<option value="${esc(x.cct)}">`).join('');$('nameList').innerHTML=[...new Set(schools.map(x=>x.nombre).filter(Boolean))].sort().map(x=>`<option value="${esc(x)}">`).join('')}
function fill(sel,arr){arr.forEach(v=>sel.add(new Option(v,v)))}
function refreshCPOptions(){const mode=$('fCPStatus').value,arr=cpGeo.features.filter(f=>mode==='without'?f.properties.inmuebles===0:f.properties.inmuebles>0).map(f=>String(f.properties.cp)).sort();const old=$('fCP').value;$('fCP').innerHTML='<option value="">Todos</option>'+arr.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(arr.includes(old))$('fCP').value=old;$('cpSearchList').innerHTML=arr.map(v=>`<option value="${esc(v)}">`).join('')}
function refreshColOptions(){const mode=$('fColStatus').value,arr=colGeo.features.filter(f=>mode==='without'?f.properties.inmuebles===0:f.properties.inmuebles>0).map(f=>({id:String(f.properties.cvegeo),label:`${f.properties.nom_asen} · ${f.properties.tipo||'Asentamiento'} · CP ${f.properties.cp||'—'}`})).sort((a,b)=>a.label.localeCompare(b.label,'es'));const old=$('fColonia').value;$('fColonia').innerHTML='<option value="">Todas</option>'+arr.map(o=>`<option value="${esc(o.id)}">${esc(o.label)}</option>`).join('');if(arr.some(x=>x.id===old))$('fColonia').value=old;$('colSearchList').innerHTML=arr.map(o=>`<option value="${esc(o.label)}" data-id="${esc(o.id)}">`).join('')}
function bind(){['fNivel','colorMode'].forEach(id=>$(id).addEventListener('change',render));$('fAlcaldia').onchange=()=>{render();activateTerritory3D('alcaldia',$('fAlcaldia').value)};$('fCPStatus').onchange=()=>{refreshCPOptions();$('fCP').value='';render();showTerritoryLayer('cp')};$('fColStatus').onchange=()=>{refreshColOptions();$('fColonia').value='';render();showTerritoryLayer('colonia')};$('fCP').onchange=()=>{render();activateTerritory3D('cp',$('fCP').value)};$('fColonia').onchange=()=>{render();activateTerritory3D('colonia',$('fColonia').value)};document.querySelectorAll('input[name=soste]').forEach(x=>x.onchange=render);$('programFilters').onchange=render;$('showCP').onchange=()=>showTerritoryLayer('cp');$('showColonias').onchange=()=>showTerritoryLayer('colonia');$('showSchools').onchange=render;$('allProg').onclick=()=>{document.querySelectorAll('#programFilters input').forEach(x=>x.checked=true);render()};$('noneProg').onclick=()=>{document.querySelectorAll('#programFilters input').forEach(x=>x.checked=false);render()};$('clearFilters').onclick=resetFilters;$('searchCCT').onchange=searchZoom;$('searchCCT').onkeydown=e=>{if(e.key==='Enter')searchZoom()};$('searchName').onchange=searchZoom;$('searchName').onkeydown=e=>{if(e.key==='Enter')searchZoom()};$('searchCP').onchange=searchTerritory;$('searchCP').onkeydown=e=>{if(e.key==='Enter')searchTerritory()};$('searchColonia').onchange=searchTerritory;$('searchColonia').onkeydown=e=>{if(e.key==='Enter')searchTerritory()};$('downloadCP').onclick=()=>downloadTerritoryList('cp');$('downloadCol').onclick=()=>downloadTerritoryList('colonia');$('closeDetail').onclick=()=>$('detail').classList.remove('open');$('fitAll').onclick=()=>{clearAlcLabels();fitGeo(alcGeo,{pitch:0,bearing:0})};$('fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');document.querySelectorAll('.navtab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('statsReset').onclick=resetFilters;$('closeModal').onclick=()=>$('inmModal').classList.remove('open');$('inmModal').onclick=e=>{if(e.target===$('inmModal'))$('inmModal').classList.remove('open')};$('goMapInm').onclick=()=>{if(currentInm){switchView('mapView');map.easeTo({center:[currentInm.lon,currentInm.lat],zoom:17,pitch:45,duration:900});$('inmModal').classList.remove('open')}};$('basemap').onchange=()=>switchBasemap($('basemap').value)}
function resetFilters(){['fAlcaldia','fNivel','fCP','fColonia','searchCCT','searchName','searchCP','searchColonia'].forEach(id=>$(id).value='');$('fCPStatus').value='with';$('fColStatus').value='with';refreshCPOptions();refreshColOptions();document.querySelectorAll('input[name=soste]').forEach(x=>x.checked=true);document.querySelectorAll('#programFilters input').forEach(x=>x.checked=false);clearAlcLabels();render();fitGeo(alcGeo,{pitch:0,bearing:0})}
function switchBasemap(mode){const center=map.getCenter(),zoom=map.getZoom(),pitch=map.getPitch(),bearing=map.getBearing();map.setStyle(mode==='dark'?darkStyle:lightStyle);$('map').classList.toggle('dark-map',mode==='dark');map.once('styledata',()=>{installMapLayers();render();map.jumpTo({center,zoom,pitch,bearing})})}
function showTerritoryLayer(type){if(!map.getLayer('cp-extrude'))return;if(type==='cp')map.setLayoutProperty('cp-extrude','visibility',($('showCP').checked||$('fCP').value||$('fCPStatus').value==='without')?'visible':'none');if(type==='colonia')map.setLayoutProperty('col-extrude','visibility',($('showColonias').checked||$('fColonia').value||$('fColStatus').value==='without')?'visible':'none')}
function state(){return {alcaldia:$('fAlcaldia').value,nivel:$('fNivel').value,cp:$('fCP').value,col:$('fColonia').value,soste:new Set([...document.querySelectorAll('input[name=soste]:checked')].map(x=>x.value)),progs:new Set([...document.querySelectorAll('#programFilters input:checked')].map(x=>x.value))}}
function filtered(){const s=state();return schools.filter(x=>{if(s.alcaldia&&x.alcaldia!==s.alcaldia)return false;if(s.nivel&&x.nivel!==s.nivel)return false;if(s.cp&&x.cp!==s.cp)return false;if(s.col&&x.cvegeo_asentamiento!==s.col)return false;if(!s.soste.has(x.sostenimiento))return false;if(s.progs.size&&!x.programas.some(p=>s.progs.has(p)))return false;return true})}
function render(){if(!meta)return;visible=filtered();const keys=new Set(buildInmuebles(visible).map(x=>x.key));visibleInm=inmuebles.filter(x=>keys.has(x.key));updateKPIs();renderSchools();renderLegend();updateSelectedProperties();renderStats();showTerritoryLayer('cp');showTerritoryLayer('colonia')}
function updateKPIs(){$('kTotal').textContent=fmt(visible.length);$('kInm').textContent=fmt(visibleInm.length);$('kPub').textContent=fmt(visible.filter(x=>x.sostenimiento==='Público').length);$('kPri').textContent=fmt(visible.filter(x=>x.sostenimiento==='Privada').length);$('kProg').textContent=fmt(visible.filter(x=>x.programas.length).length);const s=state(),parts=[];if(s.alcaldia)parts.push(s.alcaldia);if(s.cp)parts.push('CP '+s.cp);if(s.col){const f=colGeo.features.find(y=>String(y.properties.cvegeo)===String(s.col));if(f)parts.push(f.properties.nom_asen)}if(s.nivel)parts.push(s.nivel);$('scopeNote').textContent=parts.length?'Conteo actual: '+parts.join(' · '):`Base completa: ${fmt(meta.total_cct_unicos)} CCT únicos de ${fmt(meta.total_filas_fuente)} filas fuente.`}
function renderSchools(){if(!map.getSource('schools'))return;const mode=$('colorMode').value,features=$('showSchools').checked?visible.filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon)).map(x=>({type:'Feature',geometry:{type:'Point',coordinates:[x.lon,x.lat]},properties:{idx:schools.indexOf(x),color:colorFor(x,mode)}})):[];map.getSource('schools').setData({type:'FeatureCollection',features})}
const levelColors=['#2f6da5','#b05b6f','#638b48','#a06d2c','#7257a3','#2e8a89','#a45030','#55707f','#91648a','#5a7b57'];function colorFor(x,mode){if(mode==='sostenimiento')return x.sostenimiento==='Privada'?'#8b5fa5':'#1f78a8';if(mode==='programa')return x.programas.length?'#c65e2e':'#748594';const levels=meta.niveles||[];return levelColors[Math.max(0,levels.indexOf(x.nivel))%levelColors.length]}
function renderLegend(){let mode=$('colorMode').value,h='<b>Leyenda</b>';if(mode==='sostenimiento')h+='<div><i class="swatch" style="background:#1f78a8"></i>Pública</div><div><i class="swatch" style="background:#8b5fa5"></i>Privada</div>';else if(mode==='programa')h+='<div><i class="swatch" style="background:#c65e2e"></i>Con programa</div><div><i class="swatch" style="background:#748594"></i>Sin programa</div>';else h+=(meta.niveles||[]).map((n,i)=>`<div><i class="swatch" style="background:${levelColors[i%levelColors.length]}"></i>${esc(n)}</div>`).join('');$('legend').innerHTML=h}
function updateSelectedProperties(){const s=state();for(const f of alcGeo.features)f.properties.selected=s.alcaldia&&clean(f.properties.NOMGEO)===clean(s.alcaldia)?1:0;for(const f of cpGeo.features)f.properties.selected=s.cp&&String(f.properties.cp)===String(s.cp)?1:0;for(const f of colGeo.features)f.properties.selected=s.col&&String(f.properties.cvegeo)===String(s.col)?1:0;if(map.getSource('alcaldias'))map.getSource('alcaldias').setData(alcGeo);if(map.getSource('cp'))map.getSource('cp').setData(cpGeo);if(map.getSource('colonias'))map.getSource('colonias').setData(colGeo)}
function activateTerritory3D(type,value){clearAlcLabels();if(!value){if(type==='alcaldia')fitGeo(alcGeo,{pitch:0,bearing:0});return}updateSelectedProperties();let feature;if(type==='alcaldia'){feature=alcGeo.features.find(f=>clean(f.properties.NOMGEO)===clean(value));if(feature){map.setLayoutProperty('cp-extrude','visibility','none');map.setLayoutProperty('col-extrude','visibility','none');fitFeature(feature,{pitch:58,bearing:-18,maxZoom:12.4});setTimeout(()=>showAlcaldiaLabel(feature),700)}}else if(type==='cp'){feature=cpGeo.features.find(f=>String(f.properties.cp)===String(value));map.setLayoutProperty('cp-extrude','visibility','visible');map.setLayoutProperty('col-extrude','visibility','none');if(feature)fitFeature(feature,{pitch:60,bearing:-20,maxZoom:15})}else{feature=colGeo.features.find(f=>String(f.properties.cvegeo)===String(value));map.setLayoutProperty('col-extrude','visibility','visible');map.setLayoutProperty('cp-extrude','visibility','none');if(feature)fitFeature(feature,{pitch:62,bearing:-20,maxZoom:16})}}
function showAlcaldiaLabel(f){const p=f.properties,center=featureCenter(f),html=`<div class="alc-label-card"><b>${esc(p.NOMGEO)}</b><span><strong>${fmt(p.inmuebles)}</strong> inmuebles · <strong>${fmt(p.cct)}</strong> CCT</span><span>${fmt(p.publicas)} públicas · ${fmt(p.privadas)} privadas</span>${p.topniv?`<span>${esc(p.topniv)}</span>`:''}</div>`;const el=document.createElement('div');el.className='alc-stat-label';el.innerHTML=html;const mk=new maplibregl.Marker({element:el,anchor:'bottom'}).setLngLat(center).addTo(map);alcLabels.push(mk)}
function clearAlcLabels(){alcLabels.forEach(m=>m.remove());alcLabels=[]}
function searchZoom(){const c=clean($('searchCCT').value),n=clean($('searchName').value),x=schools.find(s=>(c&&clean(s.cct)===c)||(n&&clean(s.nombre)===n));if(!x)return;if(Number.isFinite(x.lat)&&Number.isFinite(x.lon)){map.easeTo({center:[x.lon,x.lat],zoom:17,pitch:45,duration:900});showDetail(x)}if(innerWidth<800)$('sidebar').classList.remove('open')}
function searchTerritory(){const cp=clean($('searchCP').value),col=clean($('searchColonia').value);if(cp){const f=cpGeo.features.find(x=>clean(x.properties.cp)===cp);if(f){$('fCPStatus').value=f.properties.inmuebles?'with':'without';refreshCPOptions();$('fCP').value=String(f.properties.cp);render();activateTerritory3D('cp',f.properties.cp);return}}if(col){const f=colGeo.features.find(x=>clean(`${x.properties.nom_asen} · ${x.properties.tipo||'Asentamiento'} · CP ${x.properties.cp||'—'}`)===col)||colGeo.features.find(x=>clean(x.properties.nom_asen)===col)||colGeo.features.find(x=>clean(x.properties.nom_asen).includes(col));if(f){$('fColStatus').value=f.properties.inmuebles?'with':'without';refreshColOptions();$('fColonia').value=String(f.properties.cvegeo);render();activateTerritory3D('colonia',f.properties.cvegeo)}}}
function showDetail(x){$('detailTitle').textContent=x.nombre||x.cct;const prog=x.programas.length?`<div class="pills">${x.programas.map(id=>{const p=programMap.get(id);return `<span class="pill" style="border-left:3px solid ${esc(p?.color||'#789')}">${esc(p?.label||id)}</span>`}).join('')}</div>`:'Sin programa vinculado en el ZIP base';$('detailBody').innerHTML=`<dl><dt>CCT</dt><dd>${esc(x.cct)}</dd><dt>Sostenimiento</dt><dd>${esc(x.sostenimiento)}</dd><dt>Nivel</dt><dd>${esc(x.nivel)}</dd><dt>Alcaldía</dt><dd>${esc(x.alcaldia)}</dd><dt>CP</dt><dd>${esc(x.cp||'Sin coincidencia espacial')}</dd><dt>Asentamiento</dt><dd>${esc(x.asentamiento||'Sin coincidencia espacial')}</dd><dt>Domicilio</dt><dd>${esc(x.domicilio||'Sin dato')}</dd><dt>Programas</dt><dd>${prog}</dd></dl>`;$('detail').classList.add('open')}
function downloadTerritoryList(type){let rows,name;if(type==='cp'){const mode=$('fCPStatus').value;rows=cpGeo.features.filter(f=>mode==='without'?f.properties.inmuebles===0:f.properties.inmuebles>0).map(f=>[f.properties.cp,f.properties.inmuebles]);name=`CP_${mode==='without'?'sin':'con'}_inmuebles.csv`;downloadCSV(name,[['CP','INMUEBLES'],...rows])}else{const mode=$('fColStatus').value;rows=colGeo.features.filter(f=>mode==='without'?f.properties.inmuebles===0:f.properties.inmuebles>0).map(f=>[f.properties.cvegeo,f.properties.nom_asen,f.properties.tipo,f.properties.cp,f.properties.inmuebles]);name=`Colonias_${mode==='without'?'sin':'con'}_inmuebles.csv`;downloadCSV(name,[['CVEGEO','COLONIA_ASENTAMIENTO','TIPO','CP','INMUEBLES'],...rows])}}
function downloadCSV(name,rows){const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},200)}
function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.navtab').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='mapView')setTimeout(()=>map.resize(),50);if(id==='statsView')renderStats()}
function renderStats(){if(!meta)return;const arr=visibleInm,s=state();$('sInm').textContent=fmt(arr.length);$('sCct').textContent=fmt(new Set(visible.map(x=>x.cct)).size);$('sCp').textContent=fmt(new Set(arr.map(x=>x.cp).filter(Boolean)).size);$('sCol').textContent=fmt(new Set(arr.map(x=>x.col).filter(Boolean)).size);const parts=[];if(s.alcaldia)parts.push(s.alcaldia);if(s.cp)parts.push('CP '+s.cp);if(s.col){const f=colGeo.features.find(y=>String(y.properties.cvegeo)===String(s.col));if(f)parts.push(f.properties.nom_asen)}if(s.nivel)parts.push(s.nivel);$('statsScope').textContent=parts.length?parts.join(' · '):'CDMX completa';$('inmCount').textContent=fmt(arr.length);renderRanking('cpTop',countTerritory(arr,'cp'),true,'cp');renderRanking('cpBottom',countTerritory(arr,'cp'),false,'cp');renderRanking('colTop',countTerritory(arr,'col'),true,'col');renderRanking('colBottom',countTerritory(arr,'col'),false,'col');renderInmuebles(arr)}
function countTerritory(arr,type){const m=new Map();for(const i of arr){const key=type==='cp'?i.cp:i.col;if(!key)continue;const label=type==='cp'?`CP ${i.cp}`:(i.asentamiento||key);if(!m.has(key))m.set(key,{key,label,count:0});m.get(key).count++}return [...m.values()]}
function renderRanking(id,data,desc,type){const d=data.sort((a,b)=>desc?b.count-a.count:a.count-b.count).slice(0,10),max=Math.max(1,...d.map(x=>x.count));$(id).innerHTML=d.length?d.map((x,i)=>`<div class="rank-row" data-key="${esc(x.key)}" data-type="${type}"><div class="rank-bar" style="width:${x.count/max*100}%"></div><div class="rank-content"><span class="rank-pos">${i+1}</span><span class="rank-name">${esc(x.label)}</span><span class="rank-value">${fmt(x.count)}</span></div></div>`).join(''):'<p class="hint">Sin datos para el filtro actual.</p>';$(id).querySelectorAll('.rank-row').forEach(r=>r.onclick=()=>selectRank(r.dataset.type,r.dataset.key))}
function selectRank(type,key){if(type==='cp'){$('fCPStatus').value='with';refreshCPOptions();$('fCP').value=key;$('fColonia').value='';$('searchCP').value=key;$('searchColonia').value=''}else{$('fColStatus').value='with';refreshColOptions();$('fColonia').value=key;$('fCP').value='';const f=colGeo.features.find(s=>String(s.properties.cvegeo)===String(key));$('searchColonia').value=f?.properties?.nom_asen||'';$('searchCP').value=''}render();switchView('mapView');setTimeout(()=>activateTerritory3D(type==='cp'?'cp':'colonia',key),80)}
function renderInmuebles(arr){const sorted=[...arr].sort((a,b)=>(a.cp||'').localeCompare(b.cp||'')||(a.asentamiento||'').localeCompare(b.asentamiento||'')||b.ccts.length-a.ccts.length);$('inmuebleList').innerHTML=sorted.length?sorted.map(i=>`<div class="inm-row" data-key="${esc(i.key)}"><strong>${esc(i.id)} · ${esc(i.asentamiento||'Sin colonia')}</strong><span>CP ${esc(i.cp||'—')} · ${esc(i.alcaldia||'—')}</span><span>${esc(i.domicilio||'Domicilio no disponible')}</span><span class="cct-badge">${i.ccts.length} CCT</span></div>`).join(''):'<p class="hint">No hay inmuebles con los filtros actuales.</p>';$('inmuebleList').querySelectorAll('.inm-row').forEach(r=>r.onclick=()=>showInmueble(r.dataset.key))}
function showInmueble(key){const i=inmuebles.find(x=>x.key===key)||visibleInm.find(x=>x.key===key);if(!i)return;currentInm=i;$('inmTitle').textContent=`${i.id} · ${i.ccts.length} CCT`;$('inmBody').innerHTML=`<div class="inm-meta"><b>Alcaldía</b><span>${esc(i.alcaldia||'—')}</span><b>CP</b><span>${esc(i.cp||'—')}</span><b>Colonia</b><span>${esc(i.asentamiento||'—')}</span><b>Domicilio</b><span>${esc(i.domicilio||'—')}</span><b>Coordenadas</b><span>${i.lat.toFixed(6)}, ${i.lon.toFixed(6)}</span></div>${i.ccts.map(c=>`<div class="cct-detail"><h4>${esc(c.cct)} · ${esc(c.nombre)}</h4><p><b>Nivel:</b> ${esc(c.nivel)} · <b>Sostenimiento:</b> ${esc(c.sostenimiento)}</p><p><b>Programas:</b> ${c.programas.length?c.programas.map(p=>esc(programMap.get(p)?.label||p)).join(', '):'Sin programa vinculado'}</p></div>`).join('')}`;$('inmModal').classList.add('open')}
function fitGeo(g,opt={}){const b=bboxGeo(g);if(!b)return;map.fitBounds([[b[0],b[1]],[b[2],b[3]]],{padding:36,duration:900,maxZoom:opt.maxZoom||12});setTimeout(()=>map.easeTo({pitch:opt.pitch??map.getPitch(),bearing:opt.bearing??map.getBearing(),duration:650}),220)}
function fitFeature(f,opt={}){fitGeo({type:'FeatureCollection',features:[f]},opt)}
function bboxGeo(g){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;const scan=c=>{if(!Array.isArray(c))return;if(typeof c[0]==='number'&&typeof c[1]==='number'){minX=Math.min(minX,c[0]);maxX=Math.max(maxX,c[0]);minY=Math.min(minY,c[1]);maxY=Math.max(maxY,c[1]);return}c.forEach(scan)};(g.features||[g]).forEach(f=>scan(f.geometry?.coordinates));return Number.isFinite(minX)?[minX,minY,maxX,maxY]:null}
function featureCenter(f){const b=bboxGeo({type:'FeatureCollection',features:[f]});return b?[(b[0]+b[2])/2,(b[1]+b[3])/2]:[-99.13,19.35]}
